name: API pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Checking API design standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stoplightio/spectral-action@v0.8.8
        with:
          file_glob: ./apis/*.yaml
          spectral_ruleset: .spectral.yaml
  validate:
    name: Validation kong files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Finding kong configurations
        id: finding-files
        run: |
          echo "::set-output name=FILELIST::$(./deployments/prod  -name '*.yaml' -print)"
      - name: Validating configurations
        run: |
          echo  ${{ steps.finding-files.outputs.FILELIST }}
  deployment:
    name: Deploy API to Kong Konnect
    runs-on: ubuntu-latest
    steps:
      - uses: kong/setup-deck@v1
      - run: deck ping --konnect-token ${{secrets.KONG_KONNECT_TOKEN}}
